export const enum Direction {
  NONE = "none",
  WALK_UP_1 = "_walk_up_1",
  WALK_UP_2 = "_walk_up_2",
  WALK_LEFT_1 = "_walk_left_1",
  WALK_LEFT_2 = "_walk_left_2",
  WALK_RIGHT_1 = "_walk_right_1",
  WALK_RIGHT_2 = "_walk_right_2",
  WALK_DOWN_1 = "_walk_down_1",
  WALK_DOWN_2 = "_walk_down_2",
  RUN_UP_1 = "_run_up_1",
  RUN_UP_2 = "_run_up_2",
  RUN_UP_3 = "_run_up_3",
  RUN_LEFT_1 = "_run_left_1",
  RUN_LEFT_2 = "_run_left_2",
  RUN_LEFT_3 = "_run_left_3",
  RUN_RIGHT_1 = "_run_right_1",
  RUN_RIGHT_2 = "_run_right_2",
  RUN_RIGHT_3 = "_run_right_3",
  RUN_DOWN_1 = "_run_down_1",
  RUN_DOWN_2 = "_run_down_2",
  RUN_DOWN_3 = "_run_down_3",
}