export const enum TEXTURE {
  WINDOW_0 = 'window_0',
  WINDOW_1 = 'window_1',
  WINDOW_2 = 'window_2',
  BG_LOBBY = 'bg_lobby',
  INPUT_LOBBY = 'input_lobby',
  PAUSE_BLACK = 'pause_black',
  PAUSE_WHITE = 'pause_white',
  BAR = 'bar',
  BAR_S = 'bar_s',
  CONTINUE = 'continue',
  CONTINUE_S = 'continue_s',
  GENDER_0 = 'gender_0',
  GENDER_1 = 'gender_1',
  SELECT = 'select',
  BOY_1_STATUE = 'boy_1_statue',
  BOY_2_STATUE = 'boy_2_statue',
  BOY_3_STATUE = 'boy_3_statue',
  BOY_4_STATUE = 'boy_4_statue',
  GIRL_1_STATUE = 'girl_1_statue',
  GIRL_2_STATUE = 'girl_2_statue',
  GIRL_3_STATUE = 'girl_3_statue',
  GIRL_4_STATUE = 'girl_4_statue',
  BOY_1_MOVEMENT = 'boy_1_movement',
  BOY_2_MOVEMENT = 'boy_2_movement',
  BOY_3_MOVEMENT = 'boy_3_movement',
  BOY_4_MOVEMENT = 'boy_4_movement',
  GIRL_1_MOVEMENT = 'girl_1_movement',
  GIRL_2_MOVEMENT = 'girl_2_movement',
  GIRL_3_MOVEMENT = 'girl_3_movement',
  GIRL_4_MOVEMENT = 'girl_4_movement',
  ARROW = 'arrow',
  BLACK = 'black',
  SEASON_0 = 'season_0',
  SEASON_1 = 'season_1',
  SEASON_2 = 'season_2',
  SEASON_3 = 'season_3',
  MAP_GROUND = 'ground_0',
  MAP_TEST = 'test_map',
  MENU_BOX = 'menu_box',
  MENU_SHOES = 'menu_shoes',
  MENU_BAG = 'menu_bag',
  MENU_POKEDEX = 'menu_pokedex',
  MENU_CARD = 'menu_card',
  MENU_CHAT = 'menu_chat',
  MENU_DOLL = 'menu_doll',
  BG_BAG = 'bg_bag',
  XBOX = 'xbox',
  ITEM_BOX = 'item_box',
  ITEM_BOX_S = 'item_box_s',
  CHOICE = 'choice',
  CHOICE_S = 'choice_s',
}

export const TEXTURE_PLAYER_MAP: Record<string, TEXTURE> = {
  BOY_1_MOVEMENT: TEXTURE.BOY_1_MOVEMENT,
  BOY_2_MOVEMENT: TEXTURE.BOY_2_MOVEMENT,
  BOY_3_MOVEMENT: TEXTURE.BOY_3_MOVEMENT,
  BOY_4_MOVEMENT: TEXTURE.BOY_4_MOVEMENT,
  GIRL_1_MOVEMENT: TEXTURE.GIRL_1_MOVEMENT,
  GIRL_2_MOVEMENT: TEXTURE.GIRL_2_MOVEMENT,
  GIRL_3_MOVEMENT: TEXTURE.GIRL_3_MOVEMENT,
  GIRL_4_MOVEMENT: TEXTURE.GIRL_4_MOVEMENT,
};
