export enum Direction {
  NONE = "none",
  WALK_UP_1 = "walk_up_1",
  WALK_UP_2 = "walk_up_2",
  WALK_LEFT_1 = "walk_left_1",
  WALK_LEFT_2 = "walk_left_2",
  WALK_RIGHT_1 = "walk_right_1",
  WALK_RIGHT_2 = "walk_right_2",
  WALK_DOWN_1 = "walk_down_1",
  WALK_DOWN_2 = "walk_down_2",
  RUN_UP_1 = "run_up_1",
  RUN_UP_2 = "run_up_2",
  RUN_UP_3 = "run_up_3",
  RUN_LEFT_1 = "run_left_1",
  RUN_LEFT_2 = "run_left_2",
  RUN_LEFT_3 = "run_left_3",
  RUN_RIGHT_1 = "run_right_1",
  RUN_RIGHT_2 = "run_right_2",
  RUN_RIGHT_3 = "run_right_3",
  RUN_DOWN_1 = "run_down_1",
  RUN_DOWN_2 = "run_down_2",
  RUN_DOWN_3 = "run_down_3",
  PET_DOWN = "follow_pokemon_down",
  PET_LEFT = "follow_pokemon_left",
  PET_RIGHT = "follow_pokemon_right",
  PET_UP = "follow_pokemon_up",
}